"""create migrations for temperature_upd

Revision ID: bf27440db30c
Revises: 5aaa833013ff
Create Date: 2026-01-10 18:33:16.980133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf27440db30c'
down_revision: Union[str, Sequence[str], None] = '5aaa833013ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.Date(), nullable=False),
    sa.Column('temperature', sa.String(length=255), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Temperature_id'), 'Temperature', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Temperature_id'), table_name='Temperature')
    op.drop_table('Temperature')
    # ### end Alembic commands ###
